#General Settings
[general]
	#If true, torches and lanterns will continue to lose fuel even while in the players inventory.
	tickInInventory = false
	#If true, certain animals will drop fat as an item, which can be used in lanterns.
	animalsDropFat = true
	#How many fuel ticks you get for a single experience point in the soul lanterns and torches. Default 4800 (4 minutes).
	# Default: 4800.0
	# Range: 1.0 ~ 1.7976931348623157E308
	soulExpRatio = 4800.0
	#How many experience points are used in a single right click. Default 1.
	# Default: 1
	# Range: > 1
	expIncrement = 1
	#How much exp points should a bottle of enchanting count as. This is multiplied by soulExpRatio. The wiki says 7 is the average.
	# Default: 7
	# Range: > 1
	bottleExpAmount = 7
	#If true, you can light torches and lanterns within the crafting inventory.
	craftLight = true
	#If true, replace torches, lanterns, etc. in loot tables with unlit versions.
	replaceInLootTables = true

#Oil Can Settings
[oil_can]
	#The maximum fuel an oil can holds, in ticks.
	# Default: 576000
	# Range: > 1
	maxCanFuel = 576000
	#Do lanterns require an oil can to be fueled?
	lanternsNeedCan = true
	#Can torches be fueled with an oil can?
	torchesUseCan = false
	#Globally modify all oil can recipes. 0.5 means all items give half as much oil.
	# Default: 1.0
	# Range: 0.0 ~ 1.7976931348623157E308
	oilRecipeMultiplier = 1.0
	#0: Craft oil using can and animal fat
	#1: Craft oil using can and coal
	#2: Both enabled
	#3: Disable recipes (You must provide custom JSON files, open the mod JAR to see format)
	# Default: 0
	# Range: 0 ~ 3
	oilRecipeType = 0

#Torch Settings
[torch]
	#How long a torch lasts when crafted. There are 20 ticks per second so 48000 ticks = 40 minutes.
	# Default: 48000
	# Range: > 1
	defaultTorchFuel = 48000
	#How long a soul torch can last without being refilled, in ticks.
	# Default: 48000
	# Range: > 1
	defaultSoulTorchFuel = 48000
	#Torches will become unlit when broken.
	torchesExtinguishWhenBroken = true
	#Overrides torchesExtinguishWhenBroken. Torches will be fully expended when broken (burnt torch or stick).
	torchesBurnWhenDropped = true
	#0: Burnt torches drop as burnt torches
	#1: Burnt torches drop as sticks
	#2: Burnt torches drop nothing
	# Default: 0
	# Range: 0 ~ 2
	burntDrop = 0
	#Torches will be affected when in the rain. Will smolder or become unlit depending on torchesSmolder.
	torchesRain = true
	#If a torch is in the rain and torchesRain = true, then it will smolder and burn fuel at 1/3rd the normal rate instead of becoming unlit.
	torchesSmolder = true
	#If true, torches must be lit after crafting.
	craftUnlit = false
	#Right click a torch without holding fuel or a lighter to unlight it.
	handUnlightTorch = false
	#0: When going underwater, torches in your inventory will be unaffected
	#1: When going underwater, torches in mainhand or offhand will be extinguished
	#2: When going underwater, torches in inventory will be extinguished
	# Default: 2
	# Range: 0 ~ 2
	invExtinguishInWater = 2
	#0: When in rain, torches in your inventory will be unaffected
	#1: When in rain, torches in mainhand or offhand will be extinguished or smolder
	#2: When in rain, torches in inventory will be extinguished or smolder
	# Default: 2
	# Range: 0 ~ 2
	invExtinguishInRain = 2
	#How many torches are crafted.
	# Default: 1
	# Range: > 1
	torchCraftAmount = 1

#Lantern Settings
[lantern]
	#If this mod also affects lanterns.
	lanternsUseFuel = true
	#The max amount of fuel a lantern can hold. There are 20 ticks per second so 144000 ticks = 60 minutes.
	# Default: 144000
	# Range: > 1
	defaultLanternFuel = 144000
	#The max amount of fuel a soul lantern can hold. There are 20 ticks per second so 144000 ticks = 60 minutes.
	# Default: 144000
	# Range: > 1
	defaultSoulLanternFuel = 144000
	#A lantern must have at least this much fuel to be ignited from unlit. Once lit it will continue to burn to 0
	# Default: 1
	# Range: > 1
	minLanternIgnitionFuel = 1
	#The amount a fuel item adds to the lantern by default
	# Default: 72000
	# Range: > 1
	defLanternFuelItem = 72000
	#Right click a lantern without holding fuel or a lighter to unlight it.
	handUnlightLantern = false
	#How much fuel a newly crafted lantern starts with.
	# Default: 0
	# Range: > 0
	startingLanternFuel = 0
	#Allow the player to pick up lanterns with sneak-clicking.
	pickUpLanterns = true

#Fire Starter Settings
[fire_starter]
	#Can the fire starter light campfires
	canLightCampfires = true
	#Can the fire starter light torches
	canLightTorches = true
	#Can the fire starter start full-block fires
	canStartFires = true
	#Can the fire starter light lanterns
	canLightLanterns = false
	#Percentage chance that the fire starter works
	# Default: 0.33
	# Range: 0.0 ~ 1.0
	starterSuccessChance = 0.33

#Campfire Settings
[campfire]
	#Whether campfires should be crafted as unlit/hardcore.
	craftHardcoreCampfire = true
	#Max fuel that can be added to a campfire
	# Default: 24000
	# Range: > 0
	campfireMaxFuel = 24000
	#Burn time for campfire fuel items is calculated by this value times its furnace duration
	# Default: 8.0
	# Range: 1.0 ~ 1.7976931348623157E308
	campfireFuelFactor = 8.0

#Compatibility Settings
[compat]
	#If true, and Farmer's Delight is installed, the Stove will be crafted as a hardcore version which needs fuel.
	craftHardcoreStove = true
	#Max torches that the Curios bandolier can hold
	# Default: 192
	# Range: > 1
	bandolierMaxTorches = 192
	#0: Placement disabled
	#1: Place by right clicking a block
	#2: Place by right clicking a block with an empty hand
	# Default: 2
	# Range: 0 ~ 2
	bandolierInteractMode = 2
	#If true, the bandolier has a crafting recipe.
	craftBandolier = true
	#If true, the bandolier appears in the creative tab.
	showBandolier = true
